### ISSUE TITLE
Broken hiera config

### ISSUE THREAD

**Issue by mlosapio** [jsok/puppet-vault#108]
https://github.com/jsok/puppet-vault/blob/14f5b544c5c5759ea6066f831addb16143e3bcd4/manifests/init.pp#L79

This has broken hiera configs 

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Syntax error at 'Hash'; expected ')' at /etc/puppet/modules/vault/manifests/init.pp:79 on node 1d32de78d8ac

```
---
classes:
  - vault

vault::storage:
  file:
    path: /tmp

vault::listener:
  - tcp:
      address: 127.0.0.1:8200
      tls_disable: 1

vault::default_lease_ttl: 720h
```

**Comment by jsok** [comment]
Which version of Puppet are you running? The error suggests you are using an old version that doesn't support Data Types.

**Comment by mlosapio** [comment]
Correct 3.6 I’ll close this out
