### ISSUE TITLE
Dependency version update for puppet-archive' (>= 1.1.2 < 2.0.0)

### ISSUE THREAD

**Issue by den-is** [jsok/puppet-vault#109]
Please update dependency for 'puppet-archive' (>= 1.1.2 < 2.0.0)
This module is v2.2.0 already.

**Comment by jsok** [comment]
`puppet-archive` 2.0 dropped Puppet 3 support, this aligns well with this modules [2.0.0 milestone](https://github.com/jsok/puppet-vault/milestone/1).
