### ISSUE TITLE
Dependency conflict with KyleAnderson/consul

### ISSUE THREAD

**Issue by traikodinev** [jsok/puppet-vault#122]
Version 1.2.8 requires puppet/archive (>= 1.1.2 < 2.0.0), however the consul puppet module (https://github.com/solarkennedy/puppet-consul) needs (>= 2.00 < 3.00). It is generally a common use case to install those two on the same machine. Puppet resolves the conflict by installing version 1.1.0 of jsok/vault.

Note vault 0.10.0 itself works fine with the older (1.1.0) version. I only found the conflict because I tried enabling the OSS UI and there is no flag for this in 1.1.0.

**Comment by jsok** [comment]
@include4eto you're right. Please submit a PR to upgrade the puppet/archive version, there's no reason it needs it can't work with v2.x.

**Comment by include4eto** [comment]
@jsok Actually it's fine on github (in metadata.json), it just needs to be updated on PuppetForge but I'm guessing that will happen in 2.0 or with the next update?

**Comment by erMaurone** [comment]
Hi @jsok thank you for your effort on this.  I was watching this space hoping to see 2.0 in PuppetForge.  Do you see it as close to ready?  I could contribute a little if it helps getting it over the line.

**Comment by jsok** [comment]
Closed by v2.0.0 release
