### ISSUE TITLE
not working with puppet 6: undefined method `sorted_json'

### ISSUE THREAD

**Issue by maxadamo** [jsok/puppet-vault#130]
`Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, undefined method 'sorted_json' for Scope(Class[Vault::Config]):Puppet::Parser::Scope (file: /etc/puppetlabs/code/environments/production/modules/vault/manifests/config.pp, line: 29, column: 16)`

The solution should be failrly easy. 
You need to use `to_json_pretty`, which you are already using on the master branch.

**Comment by jsok** [comment]
v2.0.0 released with this fix.
