### ISSUE TITLE
Doesn't support seal stanza

### ISSUE THREAD

**Issue by pmascarenhas** [jsok/puppet-vault#147]
Error: Error while evaluating a Resource Statement, Class[Vault]: has no parameter named 'seal'

**Comment by jsok** [comment]
Is this a bug report or a feature request?

**Comment by jsok** [comment]
Defining `seal` configuration can be done via the `extra_config` option:

```puppet
class { '::vault':
  extra_config => {
    'seal' => {
      'awskms' => { ... }
    }
  }
}
```
