### ISSUE TITLE
Debian Upstart

### ISSUE THREAD

**Issue by 0x9090** [jsok/puppet-vault#19]
Service provider detection seems to fail. Running on fully patched Debian Jessie, CLI version

`Error: /Stage[main]/Vault::Service/Service[vault]: Provider upstart is not functional on this host`

**Comment by jsok** [comment]
This would be because Jessie uses systemd right?

If we want to support the various Debian flavours we should probably expand the platform checks in `params.pp`.

**Comment by 0x9090** [comment]
systemd, yessir

```
 sudo stat /proc/1/exe
[sudo] password for ######:
  File: '/proc/1/exe' -> '/lib/systemd/systemd'
  Size: 0         	Blocks: 0          IO Block: 1024   symbolic link
Device: 3h/3d	Inode: 8853        Links: 1
Access: (0777/lrwxrwxrwx)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2016-03-17 12:18:53.347100208 -0700
Modify: 2015-11-23 13:10:55.655999733 -0800
Change: 2015-11-23 13:10:55.655999733 -0800
 Birth: -
```

**Comment by jsok** [comment]
This can be supported it's simply a matter of work. For now the module metadata doesn't claim to support Debian Jessie so it's not an outstanding issue.
