### ISSUE TITLE
Support for AWS Linux AMI

### ISSUE THREAD

**Issue by lotjuh** [jsok/puppet-vault#24]
Hi,

We're using the default Amazon Linux AMI which is based on the RedHat 7 system but without systemd. I patched your params.pp file to support this as well. Could you put this fix in your release version so for future updates I don't need to keep patching it? (-;
The patch is very simple, just use:
`      if ($::operatingsystemmajrelease == '6' or $::operatingsystem =~ /^[Aa]mazon$/) {`

Thanks in advance!

**Comment by jsok** [comment]
HI @lotjuh, the way to contribute to this project is by raising a Pull Request. Also be aware that if you are intending on adding support for a new platform, the PR will need to be accompanied by specs/tests.
I'll close this issue for now and look forward to seeing some contributions :)

**Comment by lotjuh** [comment]
Ah, sure, I'll have a look at how to make a test and make a pull request with the patch and test for you (-:
