### ISSUE TITLE
Conf file written with root:root access rights

### ISSUE THREAD

**Issue by sboulkour** [jsok/puppet-vault#32]
First use of this vault module : using default conf given in documentation produced a non working service.
Config file /etc/vault/config.json has benn created as root:root. As service is started with user vault, it cannot read its config and fails to start.

[root@?????? vault]# ls -l
total 4
-rw-r--r--. 1 root root 100 18 juil. 12:00 config.json

**Comment by jsok** [comment]
Hi @sboulkour , thanks for the issue report.

This indeed looks incorrect, the module should be using the `user` and `group` parameters (which default to `vault`) but it's not.

However if the file mode is 0644 (as your `ls` output suggests), then the file should definitely be readable by the `vault` user even though it's owned by `root`.

**Comment by jsok** [comment]
I've just released v0.3.0, if that doesn't fix the issue please re-open 👍

**Comment by sboulkour** [comment]
For the record, here is the error message I had with the 0.2.3 version :
`Error loading configuration from /etc/vault/config.json: stat /etc/vault/config.json: permission denied`

With 0.3.0, service is up and running from the start
(tried with an update on current VM, and from scratch with a new one : it works on both).

@jsok thks for your quick reply & fix.
