### ISSUE TITLE
RFC: Manage Access Control Policies

### ISSUE THREAD

**Issue by mdwheele** [jsok/puppet-vault#53]
Would this project be amenable to vault-specific resource types that allowed management of access control policies on the vault server? 

This may be expanded to management of mounts, seal status (i.e. run-time items that aren't necessarily part of service configuration, but may be managed all the same).

As an example considering the access control policy example [in the Vault documentation](https://www.vaultproject.io/docs/concepts/policies.html):

```
path "sys/*" {
  policy = "deny"
}

path "secret/*" {
  policy = "write"
}

path "secret/foo" {
  policy = "read"
  capabilities = ["create", "sudo"]
}

path "secret/super-secret" {
  capabilities = ["deny"]
}
```

We might make something like the following available to create a managed policy:

```puppet
vault_policy { "policy_name":
  ensure => present,
  paths => {
    "sys/*" => {
      policy => "deny"
    },
    "secret/*" => {
      policy => "write"
    },
    "secret/foo" => {
      policy => "read",
      capabilities => ["create", "sudo"]
    },
    "secret/super-secret" => {
      capabilities => ["deny"]
    }
  }
}
```

To remove the policy, we might do something similar to the following:

```puppet
vault_policy { "policy_name":
  ensure => absent
}
```

Are there any objections to exploratory work in this direction? Vault is something I've just begun working with, but in efforts to solve my own problems I would be happy to contribute.

**Comment by jsok** [comment]
I think this type of functionality is fine. My main concern around custom resources, providers, types etc is testability. Often they're just lumps of untestable Ruby code and that make me nervous.
If your code comes with decent specs I'll be more likely to merge it :)

**Comment by mdwheele** [comment]
Sounds good to me! Exactly what I expected 😄

**Comment by jsok** [comment]
Closing the issue for now, please feel free to re-open with an accompanying PR if you end up working on it.

**Comment by Luizm** [comment]
@mdwheele  Would be good if puppet-vault supported this resource, but.. you can use terraform to configure you vault service :)

https://www.terraform.io/docs/providers/vault/r/policy.html
