### ISSUE TITLE
Sort config json

### ISSUE THREAD

**Issue by idarnius** [jsok/puppet-vault#55]
Hi,

We use this module in CentOS 7 with puppet v3.8.1 and ruby 2.0.0p598.

For each puppet agent run, Vault::Config sort the lines of file /etc/vault/config.json in different order without changing the values in hiera data, and cause restart service Vault.

Is there a way to avoid this behaviour?

I see that module use function vault_sorted_json.rb

**Comment by jsok** [comment]
That's precisely the purpose of the sorted JSON function. It's used here: https://github.com/jsok/puppet-vault/blob/master/manifests/config.pp#L27

Can you possibly write a simple manifest to exercise the function manually in the same environment?

**Comment by idarnius** [comment]
I tried to write vault config in the manifest instead get values from Hiera, like [example](https://github.com/jsok/puppet-vault#examples) said , but the behaviour is the same.

Each time puppet apply configuration change some lines ( sort again ). Which is the criteria to sort and create the JSON with JSON function _vault_sorted_json_ ?

First apply puppet
```
{
   "listener": {
     "tcp": {
-      "tls_disable": 0,
-      "cluster_address": ":8201",
       "tls_cert_file": ".crt",
+      "cluster_address": ":8201",
       "tls_key_file": ".key",
-      "address": "0.0.0.0:8200"
+      "address": "0.0.0.0:8200",
+      "tls_disable": 0
     }
   },
-  "max_lease_ttl": "0h",
   "backend": {
     "consul": {
       "path": "vault/",
       "address": "500"
     }
   },
-  "default_lease_ttl": "80h"
+  "default_lease_ttl": "30h",
+  "max_lease_ttl": "80h"
 }
```

After some minutes puppet apply the configuration and change again the file.
 ```
  "default_lease_ttl": "80h",
   "listener": {
     "tcp": {
+      "tls_disable": 0,
       "cluster_address": ":8201",
-      "address": ":8200",
-      "tls_cert_file": ".crt",
       "tls_key_file": ".key",
-      "tls_disable": 0
+      "address": ":8200",
+      "tls_cert_file": ".crt"
     }
   },
   "backend": {
     "consul": {
-      "address": ":8500",
-      "path": "vault/"
+      "path": "vault/",
+      "address": ":8500"
     }
   }
```

**Comment by jsok** [comment]
I think I have found the issue, [this commit](https://github.com/jsok/puppet-vault/commit/31608bb2132efdbdb2aba8393e089f9151ce466e) made a change to convert the JSON to be more human readable. However `JSON.pretty_generate` doesn't guarantee ordering.

I'll push through a change and new version now to fix the broken behaviour.

**Comment by jsok** [comment]
Please try v1.1.6 of this module and report back if you are still encountering the issue.
