### ISSUE TITLE
Refresh acceptance tests

### ISSUE THREAD

**Issue by jsok** [jsok/puppet-vault#65]
The beaker tests have rotted a bit, main tasks are to:

 1. Get the beaker dependencies up to date
 1. Include acceptance tests in CI
 1. Include tests for all supported platforms (especially systemd-based platforms, also [Amazon Linux](https://hub.docker.com/_/amazonlinux/))

**Comment by petems** [comment]
@jsok fixed in #77

**Comment by jsok** [comment]
Fixed by #77
