### ISSUE TITLE
Allow to specify multiple tcp listeners

### ISSUE THREAD

**Issue by kasimon** [jsok/puppet-vault#88]
Using a hash for the listener makes it impossible to use multiple tcp listeners, for example to listen on localhost via HTTP and on the public address via HTTPS. I currently work around this by using 'tcp' for one and 'TCP' for the other, as puppet is case sensitive, consul isn't.

**Comment by jsok** [comment]
Good pick up, it should be an array.

```hcl
listener "tcp" {
 address = "127.0.0.1:8200"
 tls_disable = 1
}
listener "tcp" {
 address = "127.0.0.1:9200"
 tls_disable = 1
}
```

translates to

```json
{
  "listener": [
    { "tcp": { "address": "127.0.0.1:8200", "tls_disable": 1 } },
    { "tcp": { "address": "127.0.0.1:9200", "tls_disable": 1 } }
  ]
}
```

I have a PR forthcoming, but I need to think about the backwards compatibility ramifications.

**Comment by jsok** [comment]
I've opened https://github.com/jsok/puppet-vault/pull/89, would appreciate some feedback and/or testing to see if it solves your issue.
