### ISSUE TITLE
Add Archlinux support /puppet4 features

### ISSUE THREAD

**Issue by bastelfreak** [jsok/puppet-vault#94]
Hi,
I'm happy to contribute changes to make this module work on archlinux? Are you interested in this? Also I can cleanup the code and replace the legacy validate_* methods (they will be dropped in the future from stdlib) with proper puppet4 datatypes. But that would break compatibility with Puppet 3. The metadata.json says that this module still works with Puppet 3. In my opinion dropping it would be fine, since Puppet 3 is EOL and doesn't receive any (including security related) patches since one year.

**Comment by jsok** [comment]
Absolutely @bastelfreak, using proper types would be a very welcome addition.
We could make it a target for a 2.0 release and with that drop puppet 3 support too.

Archlinux support is also welcome!

**Comment by jsok** [comment]
Fixed by #96
